-- EFF_APPR_BENEFIC_ACCOMP, EFF_APPR_ABAND_TYPE_FORMATION, EFF_APPR_ABAND_SPECIALITE, EFF_APPR_SPECIALITE_SORTANTS
-- EFF_APPR_ABAND_NIVEAU_INSTRUCT, EFF_APPR_ABAND_AGE, EFF_APPR_BENEFIC_ACCOMP_2, EFFECTIF_APPR_SPECIALITE
-- EFF_APPR_BENEFIC_KITS_INSTALLATION, EFFECTIF_APPR_AGE, EFFECTIF_APPR_HANDICAPES, EFFECTIF_APPR_NIVEAU_INSTRUCTION
-- EFFECTIF_APPR_SPECIALITE, EFFECTIF_APPR_TYPE_FORMATION, EFFECTIF_APPR_TYPE_VULNERABILITE, EFFECTIF_APPR_VICT_VIOLENCES
-- =============================================
-- TABLE DE DIMENSION POUR FACTORISER LES CODES
-- =============================================
CREATE TABLE DIMENSION_APPRENANT (
    CODE_DIMENSION_APPRENANT INT IDENTITY(1,1) NOT NULL,
    
    -- Codes obligatoires (toujours présents)
    CODE_CENTRE_DELEGATION          INT NOT NULL,
    CODE_TYPE_ANNEE                 TINYINT NOT NULL,
    
    -- Codes optionnels (peuvent être 255 = non applicable)
    CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT TINYINT NOT NULL DEFAULT 255,
    CODE_TYPE_SPECIALITE            TINYINT NOT NULL DEFAULT 255,
    CODE_TYPE_DUREE_FORMATION       TINYINT NOT NULL DEFAULT 255,
    CODE_TYPE_MODALITE_ACCOMP       TINYINT NOT NULL DEFAULT 255,
    CODE_TYPE_FORMATION             TINYINT NOT NULL DEFAULT 255,
    CODE_TYPE_NIVEAU_INSTRUCTION    TINYINT NOT NULL DEFAULT 255,
    CODE_TYPE_AGE                   TINYINT NOT NULL DEFAULT 255,
    CODE_TYPE_ACCOMPAGNEMENT        TINYINT NOT NULL DEFAULT 255,
    CODE_TYPE_KITS_INSTALLATION     TINYINT NOT NULL DEFAULT 255,
    CODE_TYPE_HANDICAP              TINYINT NOT NULL DEFAULT 255,
    CODE_TYPE_MODE_FORMATION        TINYINT NOT NULL DEFAULT 255,
    CODE_TYPE_VULNERABILITE         TINYINT NOT NULL DEFAULT 255,
    CODE_TYPE_VIOLENCES             TINYINT NOT NULL DEFAULT 255,  
    -- Métadonnées
    DATE_CREATION DATETIME2 DEFAULT GETDATE(),
    DATE_MODIFICATION DATETIME2 DEFAULT GETDATE(),
    
    -- Contraintes de clés étrangères
    CONSTRAINT FK_DIM_CENTRE_DELEGATION FOREIGN KEY (CODE_CENTRE_DELEGATION) 
        REFERENCES CENTRE_DELEGATION (CODE_CENTRE_DELEGATION),
    CONSTRAINT FK_DIM_TYPE_ANNEE FOREIGN KEY (CODE_TYPE_ANNEE) 
        REFERENCES TYPE_ANNEE (CODE_TYPE_ANNEE),
    CONSTRAINT FK_DIM_TYPE_EFFECTIF_PARCOURS_APPRENANT FOREIGN KEY (CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT) 
        REFERENCES TYPE_EFFECTIF_PARCOURS_APPRENANT (CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT),
    CONSTRAINT FK_DIM_TYPE_SPECIALITE FOREIGN KEY (CODE_TYPE_SPECIALITE) 
        REFERENCES TYPE_SPECIALITE (CODE_TYPE_SPECIALITE),
    CONSTRAINT FK_DIM_TYPE_DUREE_FORMATION FOREIGN KEY (CODE_TYPE_DUREE_FORMATION) 
        REFERENCES TYPE_DUREE_FORMATION (CODE_TYPE_DUREE_FORMATION),
    CONSTRAINT FK_DIM_TYPE_MODALITE_ACCOMP FOREIGN KEY (CODE_TYPE_MODALITE_ACCOMP) 
        REFERENCES TYPE_MODALITE_ACCOMP (CODE_TYPE_MODALITE_ACCOMP),
    CONSTRAINT FK_DIM_TYPE_FORMATION FOREIGN KEY (CODE_TYPE_FORMATION) 
        REFERENCES TYPE_FORMATION (CODE_TYPE_FORMATION),
    CONSTRAINT FK_DIM_TYPE_NIVEAU_INSTRUCTION FOREIGN KEY (CODE_TYPE_NIVEAU_INSTRUCTION) 
        REFERENCES TYPE_NIVEAU_INSTRUCTION (CODE_TYPE_NIVEAU_INSTRUCTION),
    CONSTRAINT FK_DIM_TYPE_AGE FOREIGN KEY (CODE_TYPE_AGE) 
        REFERENCES TYPE_AGE (CODE_TYPE_AGE),
    CONSTRAINT FK_DIM_TYPE_ACCOMPAGNEMENT FOREIGN KEY (CODE_TYPE_ACCOMPAGNEMENT) 
        REFERENCES TYPE_ACCOMPAGNEMENT (CODE_TYPE_ACCOMPAGNEMENT),
    CONSTRAINT FK_DIM_TYPE_KITS_INSTALLATION FOREIGN KEY (CODE_TYPE_KITS_INSTALLATION) 
        REFERENCES TYPE_KITS_INSTALLATION (CODE_TYPE_KITS_INSTALLATION),
    CONSTRAINT FK_DIM_TYPE_HANDICAP FOREIGN KEY (CODE_TYPE_HANDICAP) 
        REFERENCES TYPE_HANDICAP (CODE_TYPE_HANDICAP),
    CONSTRAINT FK_DIM_TYPE_MODE_FORMATION FOREIGN KEY (CODE_TYPE_MODE_FORMATION) 
        REFERENCES TYPE_MODE_FORMATION (CODE_TYPE_MODE_FORMATION),
    CONSTRAINT FK_DIM_TYPE_VULNERABILITE FOREIGN KEY (CODE_TYPE_VULNERABILITE) 
        REFERENCES TYPE_VULNERABILITE (CODE_TYPE_VULNERABILITE),
    CONSTRAINT FK_DIM_TYPE_VIOLENCES FOREIGN KEY (CODE_TYPE_VIOLENCES) 
        REFERENCES TYPE_VIOLENCES (CODE_TYPE_VIOLENCES),

    -- Clés
    CONSTRAINT UQ_DIMENSION_APPRENANT UNIQUE (CODE_DIMENSION_APPRENANT),
    CONSTRAINT PK_DIMENSION_APPRENANT PRIMARY KEY (
        CODE_CENTRE_DELEGATION,
        CODE_TYPE_ANNEE,
        CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,
        CODE_TYPE_SPECIALITE,
        CODE_TYPE_DUREE_FORMATION,
        CODE_TYPE_MODALITE_ACCOMP,
        CODE_TYPE_FORMATION,
        CODE_TYPE_NIVEAU_INSTRUCTION,
        CODE_TYPE_AGE,
        CODE_TYPE_ACCOMPAGNEMENT,
        CODE_TYPE_KITS_INSTALLATION,
        CODE_TYPE_HANDICAP,
        CODE_TYPE_MODE_FORMATION,
        CODE_TYPE_VULNERABILITE,
        CODE_TYPE_VIOLENCES
    )
);
GO

IF OBJECT_ID('TYPE_EFFECTIFS_APPRENANTS') IS NULL
BEGIN
CREATE TABLE TYPE_EFFECTIFS_APPRENANTS (
    CODE_TYPE_EFFECTIFS_APPRENANTS TINYINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    LIBELLE_TYPE_EFFECTIFS_APPRENANTS NVARCHAR(600) NOT NULL UNIQUE
);
END

INSERT INTO TYPE_EFFECTIFS_APPRENANTS
VALUES
('Effectifs d''apprenants par modalité d''accompagnement'),
('Effectifs (parcours apprenants) - par type de formation'),
('Effectifs (parcours apprenants) - Spécialité - Durée de formation'),
('Effectifs (parcours apprenants) - Par âge'),
('Effectifs d''apprenants bénéficiaires d''accompagnement'),
('Effectifs d''apprenants bénéficiaires kits d’installation'),
('Effectifs (parcours apprenants) - Spécialité - Par âge'),
('Effectifs (parcours apprenants) - Par mode de formation'),
('Effectifs (parcours apprenants) - Par niveau d’instruction'),
('Effectifs d''apprenants par type de handicap'),
('Effectifs d''apprenants par type de vulnérabilité'),
('Effectifs d''apprenants victimes de violences')

-- =============================================
-- TABLE EFFECTIFS_APPRENANTS SIMPLIFIÉE
-- =============================================
CREATE TABLE EFFECTIFS_APPRENANTS (
    CODE_DIMENSION_APPRENANT INT NOT NULL,
    CODE_TYPE_EFFECTIFS_APPRENANTS TINYINT NOT NULL,
    -- Effectifs
    NB_APPR_G INT NULL,
    NB_APPR_F INT NULL,
    NB_APPR_T INT NULL,
    ESTIMATION TINYINT NULL,
 
    -- Clé étrangère vers la dimension
    CONSTRAINT FK_EFFECTIFS_DIMENSION FOREIGN KEY (CODE_DIMENSION_APPRENANT) 
        REFERENCES DIMENSION_APPRENANT (CODE_DIMENSION_APPRENANT),
    
    CONSTRAINT FK_EFF_TYPE_EFFECTIFS_APPRENANTS FOREIGN KEY (CODE_TYPE_EFFECTIFS_APPRENANTS)
        REFERENCES TYPE_EFFECTIFS_APPRENANTS (CODE_TYPE_EFFECTIFS_APPRENANTS),

    CONSTRAINT PK_EFFECTIFS_APPRENANTS PRIMARY KEY (
        CODE_DIMENSION_APPRENANT, 
        CODE_TYPE_EFFECTIFS_APPRENANTS
    )
);


-- =============================================
-- 1. MIGRATION EFF_APPR_BENEFIC_ACCOMP
-- =============================================

-- Pré-populer la table de dimension pour EFF_APPR_BENEFIC_ACCOMP (évite CROSS APPLY vide)
INSERT INTO DIMENSION_APPRENANT (
    CODE_CENTRE_DELEGATION, CODE_TYPE_ANNEE, CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,
    CODE_TYPE_SPECIALITE, CODE_TYPE_DUREE_FORMATION, CODE_TYPE_MODALITE_ACCOMP,
    CODE_TYPE_FORMATION, CODE_TYPE_NIVEAU_INSTRUCTION, CODE_TYPE_AGE,
    CODE_TYPE_ACCOMPAGNEMENT, CODE_TYPE_KITS_INSTALLATION, CODE_TYPE_HANDICAP,
    CODE_TYPE_MODE_FORMATION, CODE_TYPE_VULNERABILITE, CODE_TYPE_VIOLENCES
)
SELECT DISTINCT
    s.CODE_CENTRE_DELEGATION,
    s.CODE_TYPE_ANNEE,
    255 as CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,
    255 as CODE_TYPE_SPECIALITE,
    255 as CODE_TYPE_DUREE_FORMATION,
    s.CODE_TYPE_MODALITE_ACCOMP,
    255 as CODE_TYPE_FORMATION,
    255 as CODE_TYPE_NIVEAU_INSTRUCTION,
    255 as CODE_TYPE_AGE,
    255 as CODE_TYPE_ACCOMPAGNEMENT,
    255 as CODE_TYPE_KITS_INSTALLATION,
    255 as CODE_TYPE_HANDICAP,
    255 as CODE_TYPE_MODE_FORMATION,
    255 as CODE_TYPE_VULNERABILITE,
    255 as CODE_TYPE_VIOLENCES
FROM [BASE_SIGE_MINJEC].[dbo].[EFF_APPR_BENEFIC_ACCOMP] s
WHERE NOT EXISTS (
    SELECT 1 FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT, 255) = 255
      AND ISNULL(d.CODE_TYPE_SPECIALITE, 255) = 255
      AND ISNULL(d.CODE_TYPE_DUREE_FORMATION, 255) = 255
      AND ISNULL(d.CODE_TYPE_MODALITE_ACCOMP, 255) = s.CODE_TYPE_MODALITE_ACCOMP
      AND ISNULL(d.CODE_TYPE_FORMATION, 255) = 255
      AND ISNULL(d.CODE_TYPE_NIVEAU_INSTRUCTION, 255) = 255
      AND ISNULL(d.CODE_TYPE_AGE, 255) = 255
      AND ISNULL(d.CODE_TYPE_ACCOMPAGNEMENT, 255) = 255
      AND ISNULL(d.CODE_TYPE_KITS_INSTALLATION, 255) = 255
      AND ISNULL(d.CODE_TYPE_HANDICAP, 255) = 255
      AND ISNULL(d.CODE_TYPE_MODE_FORMATION, 255) = 255
      AND ISNULL(d.CODE_TYPE_VULNERABILITE, 255) = 255
      AND ISNULL(d.CODE_TYPE_VIOLENCES, 255) = 255
);

INSERT INTO EFFECTIFS_APPRENANTS (CODE_DIMENSION_APPRENANT, CODE_TYPE_EFFECTIFS_APPRENANTS, NB_APPR_G, NB_APPR_F, NB_APPR_T, ESTIMATION)
SELECT 
    d.CODE_DIMENSION_APPRENANT,
    1 AS CODE_TYPE_EFFECTIFS_APPRENANTS,
    COALESCE(s.[NB_APPRE_H], 0) as NB_APPR_G,
    COALESCE(s.[NB_APPRE_F], 0) as NB_APPR_F,
    COALESCE(s.[NB_APPRE_H], 0) + COALESCE(s.[NB_APPRE_F], 0) as NB_APPR_T,
    0
FROM [BASE_SIGE_MINJEC].[dbo].[EFF_APPR_BENEFIC_ACCOMP] s
CROSS APPLY (
    SELECT CODE_DIMENSION_APPRENANT
    FROM DIMENSION_APPRENANT
    WHERE CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT, 255) = 255
      AND ISNULL(CODE_TYPE_SPECIALITE, 255) = 255
      AND ISNULL(CODE_TYPE_DUREE_FORMATION, 255) = 255
      AND ISNULL(CODE_TYPE_MODALITE_ACCOMP, 255) = s.CODE_TYPE_MODALITE_ACCOMP
      AND ISNULL(CODE_TYPE_FORMATION, 255) = 255
      AND ISNULL(CODE_TYPE_NIVEAU_INSTRUCTION, 255) = 255
      AND ISNULL(CODE_TYPE_AGE, 255) = 255
      AND ISNULL(CODE_TYPE_ACCOMPAGNEMENT, 255) = 255
      AND ISNULL(CODE_TYPE_KITS_INSTALLATION, 255) = 255
      AND ISNULL(CODE_TYPE_HANDICAP, 255) = 255
      AND ISNULL(CODE_TYPE_MODE_FORMATION, 255) = 255
      AND ISNULL(CODE_TYPE_VULNERABILITE, 255) = 255
      AND ISNULL(CODE_TYPE_VIOLENCES, 255) = 255
) d;


-- =============================================
-- 2. MIGRATION EFF_APPR_ABAND_TYPE_FORMATION
-- =============================================
-- Pré-population de la dimension
INSERT INTO DIMENSION_APPRENANT (
    CODE_CENTRE_DELEGATION, CODE_TYPE_ANNEE, CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,
    CODE_TYPE_SPECIALITE, CODE_TYPE_DUREE_FORMATION, CODE_TYPE_MODALITE_ACCOMP,
    CODE_TYPE_FORMATION, CODE_TYPE_NIVEAU_INSTRUCTION, CODE_TYPE_AGE,
    CODE_TYPE_ACCOMPAGNEMENT, CODE_TYPE_KITS_INSTALLATION, CODE_TYPE_HANDICAP,
    CODE_TYPE_MODE_FORMATION, CODE_TYPE_VULNERABILITE, CODE_TYPE_VIOLENCES
)
SELECT DISTINCT
    s.CODE_CENTRE_DELEGATION,
    s.CODE_TYPE_ANNEE,
    2,
    255, 255, 255,
    s.CODE_TYPE_FORMATION,
    255, 255,
    255, 255, 255,
    255, 255, 255
FROM [BASE_SIGE_MINJEC].[dbo].[EFF_APPR_ABAND_TYPE_FORMATION] s
WHERE NOT EXISTS (
    SELECT 1 FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = 2
      AND ISNULL(d.CODE_TYPE_FORMATION,255) = ISNULL(s.CODE_TYPE_FORMATION,255)
);
-- Insertion effectifs
INSERT INTO EFFECTIFS_APPRENANTS (CODE_DIMENSION_APPRENANT, CODE_TYPE_EFFECTIFS_APPRENANTS, NB_APPR_G, NB_APPR_F, NB_APPR_T, ESTIMATION)
SELECT 
    d.CODE_DIMENSION_APPRENANT,
    2 AS CODE_TYPE_EFFECTIFS_APPRENANTS,
    COALESCE(s.NB_APPR_ABAND_TYPE_FORM_G,0),
    COALESCE(s.NB_APPR_ABAND_TYPE_FORM_F,0),
    COALESCE(s.NB_APPR_ABAND_TYPE_FORM_T, COALESCE(s.NB_APPR_ABAND_TYPE_FORM_G,0)+COALESCE(s.NB_APPR_ABAND_TYPE_FORM_F,0)),
    CAST(ISNULL(s.ESTIMATION,0) AS TINYINT)
FROM [BASE_SIGE_MINJEC].[dbo].[EFF_APPR_ABAND_TYPE_FORMATION] s
CROSS APPLY (
    SELECT CODE_DIMENSION_APPRENANT FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = 2
      AND ISNULL(d.CODE_TYPE_FORMATION,255) = ISNULL(s.CODE_TYPE_FORMATION,255)
) d;

-- =============================================
-- 3. MIGRATION EFF_APPR_ABAND_SPECIALITE
-- =============================================
-- Pré-population de la dimension
INSERT INTO DIMENSION_APPRENANT (
    CODE_CENTRE_DELEGATION, CODE_TYPE_ANNEE, CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,
    CODE_TYPE_SPECIALITE, CODE_TYPE_DUREE_FORMATION, CODE_TYPE_MODALITE_ACCOMP,
    CODE_TYPE_FORMATION, CODE_TYPE_NIVEAU_INSTRUCTION, CODE_TYPE_AGE,
    CODE_TYPE_ACCOMPAGNEMENT, CODE_TYPE_KITS_INSTALLATION, CODE_TYPE_HANDICAP,
    CODE_TYPE_MODE_FORMATION, CODE_TYPE_VULNERABILITE, CODE_TYPE_VIOLENCES
)
SELECT DISTINCT
    s.CODE_CENTRE_DELEGATION,
    s.CODE_TYPE_ANNEE,
    2,
    s.CODE_TYPE_SPECIALITE,
    s.CODE_TYPE_DUREE_FORMATION,
    255,
    255, 255, 255,
    255, 255, 255,
    255, 255, 255
FROM [BASE_SIGE_MINJEC].[dbo].[EFF_APPR_ABAND_SPECIALITE] s
WHERE NOT EXISTS (
    SELECT 1 FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = 2
      AND ISNULL(d.CODE_TYPE_SPECIALITE,255) = ISNULL(s.CODE_TYPE_SPECIALITE,255)
      AND ISNULL(d.CODE_TYPE_DUREE_FORMATION,255) = ISNULL(s.CODE_TYPE_DUREE_FORMATION,255)
);
-- Insertion effectifs
INSERT INTO EFFECTIFS_APPRENANTS (CODE_DIMENSION_APPRENANT, CODE_TYPE_EFFECTIFS_APPRENANTS, NB_APPR_G, NB_APPR_F, NB_APPR_T, ESTIMATION)
SELECT 
    d.CODE_DIMENSION_APPRENANT,
    3 AS CODE_TYPE_EFFECTIFS_APPRENANTS,
    COALESCE(s.NB_APPR_ABAND_SPECIALITE_G,0),
    COALESCE(s.NB_APPR_ABAND_SPECIALITE_F,0),
    COALESCE(s.NB_APPR_ABAND_SPECIALITE_T, COALESCE(s.NB_APPR_ABAND_SPECIALITE_G,0)+COALESCE(s.NB_APPR_ABAND_SPECIALITE_F,0)),
    CAST(ISNULL(s.ESTIMATION,0) AS TINYINT)
FROM [BASE_SIGE_MINJEC].[dbo].[EFF_APPR_ABAND_SPECIALITE] s
CROSS APPLY (
    SELECT CODE_DIMENSION_APPRENANT FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = 2
      AND ISNULL(d.CODE_TYPE_SPECIALITE,255) = ISNULL(s.CODE_TYPE_SPECIALITE,255)
      AND ISNULL(d.CODE_TYPE_DUREE_FORMATION,255) = ISNULL(s.CODE_TYPE_DUREE_FORMATION,255)
) d;

-- =============================================
-- 4. MIGRATION EFF_APPR_SPECIALITE_SORTANTS
-- =============================================
-- Pré-population de la dimension
INSERT INTO DIMENSION_APPRENANT (
    CODE_CENTRE_DELEGATION, CODE_TYPE_ANNEE, CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,
    CODE_TYPE_SPECIALITE, CODE_TYPE_DUREE_FORMATION, CODE_TYPE_MODALITE_ACCOMP,
    CODE_TYPE_FORMATION, CODE_TYPE_NIVEAU_INSTRUCTION, CODE_TYPE_AGE,
    CODE_TYPE_ACCOMPAGNEMENT, CODE_TYPE_KITS_INSTALLATION, CODE_TYPE_HANDICAP,
    CODE_TYPE_MODE_FORMATION, CODE_TYPE_VULNERABILITE, CODE_TYPE_VIOLENCES
)
SELECT DISTINCT
    s.CODE_CENTRE_DELEGATION,
    s.CODE_TYPE_ANNEE,
    3,
    s.CODE_TYPE_SPECIALITE,
    s.CODE_TYPE_DUREE_FORMATION,
    255,
    255, 255, 255,
    255, 255, 255,
    255, 255, 255
FROM [BASE_SIGE_MINJEC].[dbo].[EFF_APPR_SPECIALITE_SORTANTS] s
WHERE NOT EXISTS (
    SELECT 1 FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = 3
      AND ISNULL(d.CODE_TYPE_SPECIALITE,255) = ISNULL(s.CODE_TYPE_SPECIALITE,255)
      AND ISNULL(d.CODE_TYPE_DUREE_FORMATION,255) = ISNULL(s.CODE_TYPE_DUREE_FORMATION,255)
);
-- Insertion effectifs
INSERT INTO EFFECTIFS_APPRENANTS (CODE_DIMENSION_APPRENANT, CODE_TYPE_EFFECTIFS_APPRENANTS, NB_APPR_G, NB_APPR_F, NB_APPR_T, ESTIMATION)
SELECT 
    d.CODE_DIMENSION_APPRENANT,
    3 AS CODE_TYPE_EFFECTIFS_APPRENANTS,
    COALESCE(s.NB_APPR_SORT_G,0),
    COALESCE(s.NB_APPR_SORT_F,0),
    COALESCE(s.NB_APPR_SORT_T, COALESCE(s.NB_APPR_SORT_G,0)+COALESCE(s.NB_APPR_SORT_F,0)),
    CAST(ISNULL(s.ESTIMATION,0) AS TINYINT)
FROM [BASE_SIGE_MINJEC].[dbo].[EFF_APPR_SPECIALITE_SORTANTS] s
CROSS APPLY (
    SELECT CODE_DIMENSION_APPRENANT FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = 3
      AND ISNULL(d.CODE_TYPE_SPECIALITE,255) = ISNULL(s.CODE_TYPE_SPECIALITE,255)
      AND ISNULL(d.CODE_TYPE_DUREE_FORMATION,255) = ISNULL(s.CODE_TYPE_DUREE_FORMATION,255)
) d;

-- =============================================
-- 5. MIGRATION EFF_APPR_ABAND_AGE
-- =============================================
-- Pré-population de la dimension
INSERT INTO DIMENSION_APPRENANT (
    CODE_CENTRE_DELEGATION, CODE_TYPE_ANNEE, CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,
    CODE_TYPE_SPECIALITE, CODE_TYPE_DUREE_FORMATION, CODE_TYPE_MODALITE_ACCOMP,
    CODE_TYPE_FORMATION, CODE_TYPE_NIVEAU_INSTRUCTION, CODE_TYPE_AGE,
    CODE_TYPE_ACCOMPAGNEMENT, CODE_TYPE_KITS_INSTALLATION, CODE_TYPE_HANDICAP,
    CODE_TYPE_MODE_FORMATION, CODE_TYPE_VULNERABILITE, CODE_TYPE_VIOLENCES
)
SELECT DISTINCT
    s.CODE_CENTRE_DELEGATION,
    s.CODE_TYPE_ANNEE,
    2,
    255, 255, 255,
    255, 255,
    s.CODE_TYPE_AGE,
    255, 255, 255,
    255, 255, 255
FROM [BASE_SIGE_MINJEC].[dbo].[EFF_APPR_ABAND_AGE] s
WHERE NOT EXISTS (
    SELECT 1 FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = 2
      AND ISNULL(d.CODE_TYPE_AGE,255) = ISNULL(s.CODE_TYPE_AGE,255)
);
-- Insertion effectifs
INSERT INTO EFFECTIFS_APPRENANTS (CODE_DIMENSION_APPRENANT, CODE_TYPE_EFFECTIFS_APPRENANTS, NB_APPR_G, NB_APPR_F, NB_APPR_T, ESTIMATION)
SELECT 
    d.CODE_DIMENSION_APPRENANT,
    4 AS CODE_TYPE_EFFECTIFS_APPRENANTS,
    COALESCE(s.NB_APPR_ABAND_AGE_G,0),
    COALESCE(s.NB_APPR_ABAND_AGE_F,0),
    COALESCE(s.NB_APPR_ABAND_AGE_T, COALESCE(s.NB_APPR_ABAND_AGE_G,0)+COALESCE(s.NB_APPR_ABAND_AGE_F,0)),
    CAST(ISNULL(s.ESTIMATION,0) AS TINYINT)
FROM [BASE_SIGE_MINJEC].[dbo].[EFF_APPR_ABAND_AGE] s
CROSS APPLY (
    SELECT CODE_DIMENSION_APPRENANT FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = 2
      AND ISNULL(d.CODE_TYPE_AGE,255) = ISNULL(s.CODE_TYPE_AGE,255)
) d;

-- =============================================
-- 6. MIGRATION EFF_APPR_BENEFIC_ACCOMP_2
-- =============================================
-- Pré-population de la dimension
INSERT INTO DIMENSION_APPRENANT (
    CODE_CENTRE_DELEGATION, CODE_TYPE_ANNEE, CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,
    CODE_TYPE_SPECIALITE, CODE_TYPE_DUREE_FORMATION, CODE_TYPE_MODALITE_ACCOMP,
    CODE_TYPE_FORMATION, CODE_TYPE_NIVEAU_INSTRUCTION, CODE_TYPE_AGE,
    CODE_TYPE_ACCOMPAGNEMENT, CODE_TYPE_KITS_INSTALLATION, CODE_TYPE_HANDICAP,
    CODE_TYPE_MODE_FORMATION, CODE_TYPE_VULNERABILITE, CODE_TYPE_VIOLENCES
)
SELECT DISTINCT
    s.CODE_CENTRE_DELEGATION,
    s.CODE_TYPE_ANNEE,
    255,
    255, 255, 255,
    255, 255, 255,
    s.CODE_TYPE_ACCOMPAGNEMENT,
    255, 255,
    255, 255, 255
FROM [BASE_SIGE_MINJEC].[dbo].[EFF_APPR_BENEFIC_ACCOMP_2] s
WHERE NOT EXISTS (
    SELECT 1 FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = 255
      AND ISNULL(d.CODE_TYPE_ACCOMPAGNEMENT,255) = ISNULL(s.CODE_TYPE_ACCOMPAGNEMENT,255)
);
-- Insertion effectifs
INSERT INTO EFFECTIFS_APPRENANTS (CODE_DIMENSION_APPRENANT, CODE_TYPE_EFFECTIFS_APPRENANTS, NB_APPR_G, NB_APPR_F, NB_APPR_T, ESTIMATION)
SELECT 
    d.CODE_DIMENSION_APPRENANT,
    5 AS CODE_TYPE_EFFECTIFS_APPRENANTS,
    COALESCE(s.NB_APPRE_H,0),
    COALESCE(s.NB_APPRE_F,0),
    COALESCE(s.NB_APPRE_T, COALESCE(s.NB_APPRE_H,0)+COALESCE(s.NB_APPRE_F,0)),
    CAST(ISNULL(s.ESTIMATION,0) AS TINYINT)
FROM [BASE_SIGE_MINJEC].[dbo].[EFF_APPR_BENEFIC_ACCOMP_2] s
CROSS APPLY (
    SELECT CODE_DIMENSION_APPRENANT FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = 255
      AND ISNULL(d.CODE_TYPE_ACCOMPAGNEMENT,255) = ISNULL(s.CODE_TYPE_ACCOMPAGNEMENT,255)
) d;

-- =============================================
-- 7. MIGRATION EFF_APPR_BENEFIC_KITS_INSTALLATION
-- =============================================
-- Pré-population de la dimension
INSERT INTO DIMENSION_APPRENANT (
    CODE_CENTRE_DELEGATION, CODE_TYPE_ANNEE, CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,
    CODE_TYPE_SPECIALITE, CODE_TYPE_DUREE_FORMATION, CODE_TYPE_MODALITE_ACCOMP,
    CODE_TYPE_FORMATION, CODE_TYPE_NIVEAU_INSTRUCTION, CODE_TYPE_AGE,
    CODE_TYPE_ACCOMPAGNEMENT, CODE_TYPE_KITS_INSTALLATION, CODE_TYPE_HANDICAP,
    CODE_TYPE_MODE_FORMATION, CODE_TYPE_VULNERABILITE, CODE_TYPE_VIOLENCES
)
SELECT DISTINCT
    s.CODE_CENTRE_DELEGATION,
    s.CODE_TYPE_ANNEE,
    255,
    255, 255, 255,
    255, 255, 255,
    255,
    s.CODE_TYPE_KITS_INSTALLATION,
    255,
    255, 255, 255
FROM [BASE_SIGE_MINJEC].[dbo].[EFF_APPR_BENEFIC_KITS_INSTALLATION] s
WHERE NOT EXISTS (
    SELECT 1 FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = 255
      AND ISNULL(d.CODE_TYPE_KITS_INSTALLATION,255) = ISNULL(s.CODE_TYPE_KITS_INSTALLATION,255)
);
-- Insertion effectifs
INSERT INTO EFFECTIFS_APPRENANTS (CODE_DIMENSION_APPRENANT, CODE_TYPE_EFFECTIFS_APPRENANTS, NB_APPR_G, NB_APPR_F, NB_APPR_T, ESTIMATION)
SELECT 
    d.CODE_DIMENSION_APPRENANT,
    6 AS CODE_TYPE_EFFECTIFS_APPRENANTS,
    COALESCE(s.NB_APPR_G,0),
    COALESCE(s.NB_APPR_F,0),
    COALESCE(s.NB_APPR_T, COALESCE(s.NB_APPR_G,0)+COALESCE(s.NB_APPR_F,0)),
    CAST(ISNULL(s.ESTIMATION,0) AS TINYINT)
FROM [BASE_SIGE_MINJEC].[dbo].[EFF_APPR_BENEFIC_KITS_INSTALLATION] s
CROSS APPLY (
    SELECT CODE_DIMENSION_APPRENANT FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = 255
      AND ISNULL(d.CODE_TYPE_KITS_INSTALLATION,255) = ISNULL(s.CODE_TYPE_KITS_INSTALLATION,255)
) d;

-- =============================================
-- 8. MIGRATION EFFECTIF_APPR_AGE
-- =============================================
-- Pré-population de la dimension
INSERT INTO DIMENSION_APPRENANT (
    CODE_CENTRE_DELEGATION, CODE_TYPE_ANNEE, CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,
    CODE_TYPE_SPECIALITE, CODE_TYPE_DUREE_FORMATION, CODE_TYPE_MODALITE_ACCOMP,
    CODE_TYPE_FORMATION, CODE_TYPE_NIVEAU_INSTRUCTION, CODE_TYPE_AGE,
    CODE_TYPE_ACCOMPAGNEMENT, CODE_TYPE_KITS_INSTALLATION, CODE_TYPE_HANDICAP,
    CODE_TYPE_MODE_FORMATION, CODE_TYPE_VULNERABILITE, CODE_TYPE_VIOLENCES
)
SELECT DISTINCT
    s.CODE_CENTRE_DELEGATION,
    s.CODE_TYPE_ANNEE,
    s.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,
    s.CODE_TYPE_SPECIALITE,
    255, 255,
    255, 255,
    s.CODE_TYPE_AGE,
    255, 255, 255,
    255, 255, 255
FROM [BASE_SIGE_MINJEC].[dbo].[EFFECTIF_APPR_AGE] s
WHERE NOT EXISTS (
    SELECT 1 FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = ISNULL(s.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255)
      AND ISNULL(d.CODE_TYPE_SPECIALITE,255) = ISNULL(s.CODE_TYPE_SPECIALITE,255)
      AND ISNULL(d.CODE_TYPE_AGE,255) = ISNULL(s.CODE_TYPE_AGE,255)
);
-- Insertion effectifs
INSERT INTO EFFECTIFS_APPRENANTS (CODE_DIMENSION_APPRENANT, CODE_TYPE_EFFECTIFS_APPRENANTS, NB_APPR_G, NB_APPR_F, NB_APPR_T, ESTIMATION)
SELECT 
    d.CODE_DIMENSION_APPRENANT,
    7 AS CODE_TYPE_EFFECTIFS_APPRENANTS,
    COALESCE(s.NB_EFF_ENTR_G,0),
    COALESCE(s.NB_EFF_ENTR_F,0),
    COALESCE(s.NB_EFF_ENTR_T, COALESCE(s.NB_EFF_ENTR_G,0)+COALESCE(s.NB_EFF_ENTR_F,0)),
    CAST(ISNULL(s.ESTIMATION,0) AS TINYINT)
FROM [BASE_SIGE_MINJEC].[dbo].[EFFECTIF_APPR_AGE] s
CROSS APPLY (
    SELECT CODE_DIMENSION_APPRENANT FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = ISNULL(s.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255)
      AND ISNULL(d.CODE_TYPE_SPECIALITE,255) = ISNULL(s.CODE_TYPE_SPECIALITE,255)
      AND ISNULL(d.CODE_TYPE_AGE,255) = ISNULL(s.CODE_TYPE_AGE,255)
) d;

-- =============================================
-- 9. MIGRATION EFFECTIF_APPR_MODE_FORM
-- =============================================
-- Pré-population de la dimension
INSERT INTO DIMENSION_APPRENANT (
    CODE_CENTRE_DELEGATION, CODE_TYPE_ANNEE, CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,
    CODE_TYPE_SPECIALITE, CODE_TYPE_DUREE_FORMATION, CODE_TYPE_MODALITE_ACCOMP,
    CODE_TYPE_FORMATION, CODE_TYPE_NIVEAU_INSTRUCTION, CODE_TYPE_AGE,
    CODE_TYPE_ACCOMPAGNEMENT, CODE_TYPE_KITS_INSTALLATION, CODE_TYPE_HANDICAP,
    CODE_TYPE_MODE_FORMATION, CODE_TYPE_VULNERABILITE, CODE_TYPE_VIOLENCES
)
SELECT DISTINCT
    s.CODE_CENTRE_DELEGATION,
    s.CODE_TYPE_ANNEE,
    s.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,
    255, 255, 255,
    255, 255, 255,
    255, 255, 255,
    s.CODE_TYPE_MODE_FORMATION,
    255, 255
FROM [BASE_SIGE_MINJEC].[dbo].[EFFECTIF_APPR_MODE_FORM] s
WHERE NOT EXISTS (
    SELECT 1 FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = ISNULL(s.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255)
      AND ISNULL(d.CODE_TYPE_MODE_FORMATION,255) = ISNULL(s.CODE_TYPE_MODE_FORMATION,255)
);
-- Insertion effectifs
INSERT INTO EFFECTIFS_APPRENANTS (CODE_DIMENSION_APPRENANT, CODE_TYPE_EFFECTIFS_APPRENANTS, NB_APPR_G, NB_APPR_F, NB_APPR_T, ESTIMATION)
SELECT 
    d.CODE_DIMENSION_APPRENANT,
    8 AS CODE_TYPE_EFFECTIFS_APPRENANTS,
    COALESCE(s.EFF_APPR_G,0),
    COALESCE(s.EFF_APPR_F,0),
    COALESCE(s.EFF_APPR_T, COALESCE(s.EFF_APPR_G,0)+COALESCE(s.EFF_APPR_F,0)),
    CAST(ISNULL(s.ESTIMATION,0) AS TINYINT)
FROM [BASE_SIGE_MINJEC].[dbo].[EFFECTIF_APPR_MODE_FORM] s
CROSS APPLY (
    SELECT CODE_DIMENSION_APPRENANT FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = ISNULL(s.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255)
      AND ISNULL(d.CODE_TYPE_MODE_FORMATION,255) = ISNULL(s.CODE_TYPE_MODE_FORMATION,255)
) d;

-- =============================================
-- 10. MIGRATION EFFECTIF_APPR_SPECIALITE
-- =============================================
-- Pré-population
-- INSERT INTO DIMENSION_APPRENANT (
--     CODE_CENTRE_DELEGATION, CODE_TYPE_ANNEE, CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,
--     CODE_TYPE_SPECIALITE, CODE_TYPE_DUREE_FORMATION, CODE_TYPE_MODALITE_ACCOMP,
--     CODE_TYPE_FORMATION, CODE_TYPE_NIVEAU_INSTRUCTION, CODE_TYPE_AGE,
--     CODE_TYPE_ACCOMPAGNEMENT, CODE_TYPE_KITS_INSTALLATION, CODE_TYPE_HANDICAP,
--     CODE_TYPE_MODE_FORMATION, CODE_TYPE_VULNERABILITE, CODE_TYPE_VIOLENCES
-- )
-- SELECT DISTINCT
--     s.CODE_CENTRE_DELEGATION,
--     s.CODE_TYPE_ANNEE,
--     s.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,
--     s.CODE_TYPE_SPECIALITE,
--     s.CODE_TYPE_DUREE_FORMATION, 255,
--     255, 255, 255, 
--     255, 255, 255, 
--     255, 255, 255
-- FROM [BASE_SIGE_MINJEC].[dbo].[EFFECTIF_APPR_SPECIALITE] s
-- WHERE NOT EXISTS (
--     SELECT 1 FROM DIMENSION_APPRENANT d
--     WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
--       AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
--       AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = ISNULL(s.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255)
--       AND ISNULL(d.CODE_TYPE_SPECIALITE,255) = ISNULL(s.CODE_TYPE_SPECIALITE,255)
--       AND ISNULL(d.CODE_TYPE_DUREE_FORMATION,255) = ISNULL(s.CODE_TYPE_DUREE_FORMATION,255)
-- );
-- Insertion
-- INSERT INTO EFFECTIFS_APPRENANTS (CODE_DIMENSION_APPRENANT, CODE_TYPE_EFFECTIFS_APPRENANTS, NB_APPR_G, NB_APPR_F, NB_APPR_T, ESTIMATION)
-- SELECT 
--     d.CODE_DIMENSION_APPRENANT,
--     3 AS CODE_TYPE_EFFECTIFS_APPRENANTS,
--     COALESCE(s.NB_APPR_ENT_G,0),
--     COALESCE(s.NB_APPR_ENT_F,0),
--     COALESCE(s.NB_APPR_ENT_T, COALESCE(s.NB_APPR_ENT_G,0)+COALESCE(s.NB_APPR_ENT_F,0)),
--     CAST(ISNULL(s.ESTIMATION,0) AS TINYINT)
-- FROM [BASE_SIGE_MINJEC].[dbo].[EFFECTIF_APPR_SPECIALITE] s
-- CROSS APPLY (
--     SELECT CODE_DIMENSION_APPRENANT FROM DIMENSION_APPRENANT d
--     WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
--       AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
--       AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = ISNULL(s.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255)
--       AND ISNULL(d.CODE_TYPE_SPECIALITE,255) = ISNULL(s.CODE_TYPE_SPECIALITE,255)
--       AND ISNULL(d.CODE_TYPE_DUREE_FORMATION,255) = ISNULL(s.CODE_TYPE_DUREE_FORMATION,255)
-- ) d;

-- =============================================
-- 11. MIGRATION EFF_APPR_ABAND_NIVEAU_INSTRUCT
-- =============================================
-- Pré-population (Parcours = 2)
INSERT INTO DIMENSION_APPRENANT (
    CODE_CENTRE_DELEGATION, CODE_TYPE_ANNEE, CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,
    CODE_TYPE_SPECIALITE, CODE_TYPE_DUREE_FORMATION, CODE_TYPE_MODALITE_ACCOMP,
    CODE_TYPE_FORMATION, CODE_TYPE_NIVEAU_INSTRUCTION, CODE_TYPE_AGE,
    CODE_TYPE_ACCOMPAGNEMENT, CODE_TYPE_KITS_INSTALLATION, CODE_TYPE_HANDICAP,
    CODE_TYPE_MODE_FORMATION, CODE_TYPE_VULNERABILITE, CODE_TYPE_VIOLENCES
)
SELECT DISTINCT
    s.CODE_CENTRE_DELEGATION,
    s.CODE_TYPE_ANNEE,
    2,
    255, 255, 255,
    255, s.CODE_TYPE_NIVEAU_INSTRUCTION, 255,
    255, 255, 255,
    255, 255, 255
FROM [BASE_SIGE_MINJEC].[dbo].[EFF_APPR_ABAND_NIVEAU_INSTRUCT] s
WHERE NOT EXISTS (
    SELECT 1 FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = 2
      AND ISNULL(d.CODE_TYPE_NIVEAU_INSTRUCTION,255) = ISNULL(s.CODE_TYPE_NIVEAU_INSTRUCTION,255)
);
-- Insertion
INSERT INTO EFFECTIFS_APPRENANTS (CODE_DIMENSION_APPRENANT, CODE_TYPE_EFFECTIFS_APPRENANTS, NB_APPR_G, NB_APPR_F, NB_APPR_T, ESTIMATION)
SELECT 
    d.CODE_DIMENSION_APPRENANT,
    9 AS CODE_TYPE_EFFECTIFS_APPRENANTS,
    COALESCE(s.NB_APPR_ABAND_NIV_INSTRUC_G,0),
    COALESCE(s.NB_APPR_ABAND_NIV_INSTRUC_F,0),
    COALESCE(s.NB_APPR_ABAND_NIV_INSTRUC_T, COALESCE(s.NB_APPR_ABAND_NIV_INSTRUC_G,0)+COALESCE(s.NB_APPR_ABAND_NIV_INSTRUC_F,0)),
    CAST(ISNULL(s.ESTIMATION,0) AS TINYINT)
FROM [BASE_SIGE_MINJEC].[dbo].[EFF_APPR_ABAND_NIVEAU_INSTRUCT] s
CROSS APPLY (
    SELECT CODE_DIMENSION_APPRENANT FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = 2
      AND ISNULL(d.CODE_TYPE_NIVEAU_INSTRUCTION,255) = ISNULL(s.CODE_TYPE_NIVEAU_INSTRUCTION,255)
) d;

-- =============================================
-- 12. MIGRATION EFFECTIF_APPR_HANDICAPES
-- =============================================
-- Pré-population (Parcours = 255)
INSERT INTO DIMENSION_APPRENANT (
    CODE_CENTRE_DELEGATION, CODE_TYPE_ANNEE, CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,
    CODE_TYPE_SPECIALITE, CODE_TYPE_DUREE_FORMATION, CODE_TYPE_MODALITE_ACCOMP,
    CODE_TYPE_FORMATION, CODE_TYPE_NIVEAU_INSTRUCTION, CODE_TYPE_AGE,
    CODE_TYPE_ACCOMPAGNEMENT, CODE_TYPE_KITS_INSTALLATION, CODE_TYPE_HANDICAP,
    CODE_TYPE_MODE_FORMATION, CODE_TYPE_VULNERABILITE, CODE_TYPE_VIOLENCES
)
SELECT DISTINCT
    s.CODE_CENTRE_DELEGATION,
    s.CODE_TYPE_ANNEE,
    255,
    255, 255, 255,
    255, 255, 255,
    255, 255, s.CODE_TYPE_HANDICAP,
    255, 255, 255
FROM [BASE_SIGE_MINJEC].[dbo].[EFFECTIF_APPR_HANDICAPES] s
WHERE NOT EXISTS (
    SELECT 1 FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = 255
      AND ISNULL(d.CODE_TYPE_HANDICAP,255) = ISNULL(s.CODE_TYPE_HANDICAP,255)
);
-- Insertion
INSERT INTO EFFECTIFS_APPRENANTS (CODE_DIMENSION_APPRENANT, CODE_TYPE_EFFECTIFS_APPRENANTS, NB_APPR_G, NB_APPR_F, NB_APPR_T, ESTIMATION)
SELECT 
    d.CODE_DIMENSION_APPRENANT,
    10 AS CODE_TYPE_EFFECTIFS_APPRENANTS,
    COALESCE(s.NB_APPR_HANDIC_G,0),
    COALESCE(s.NB_APPR_HANDIC_F,0),
    COALESCE(s.NB_APPR_HANDIC_T, COALESCE(s.NB_APPR_HANDIC_G,0)+COALESCE(s.NB_APPR_HANDIC_F,0)),
    CAST(ISNULL(s.ESTIMATION,0) AS TINYINT)
FROM [BASE_SIGE_MINJEC].[dbo].[EFFECTIF_APPR_HANDICAPES] s
CROSS APPLY (
    SELECT CODE_DIMENSION_APPRENANT FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = 255
      AND ISNULL(d.CODE_TYPE_HANDICAP,255) = ISNULL(s.CODE_TYPE_HANDICAP,255)
) d;

-- =============================================
-- 13. MIGRATION EFFECTIF_APPR_TYPE_VULNERABILITE
-- =============================================
-- Pré-population (Parcours = 255)
INSERT INTO DIMENSION_APPRENANT (
    CODE_CENTRE_DELEGATION, CODE_TYPE_ANNEE, CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,
    CODE_TYPE_SPECIALITE, CODE_TYPE_DUREE_FORMATION, CODE_TYPE_MODALITE_ACCOMP,
    CODE_TYPE_FORMATION, CODE_TYPE_NIVEAU_INSTRUCTION, CODE_TYPE_AGE,
    CODE_TYPE_ACCOMPAGNEMENT, CODE_TYPE_KITS_INSTALLATION, CODE_TYPE_HANDICAP,
    CODE_TYPE_MODE_FORMATION, CODE_TYPE_VULNERABILITE, CODE_TYPE_VIOLENCES
)
SELECT DISTINCT
    s.CODE_CENTRE_DELEGATION,
    s.CODE_TYPE_ANNEE,
    255,
    255, 255, 255,
    255, 255, 255,
    255, 255, 255,
    255, s.CODE_TYPE_VULNERABILITE, 255
FROM [BASE_SIGE_MINJEC].[dbo].[EFFECTIF_APPR_TYPE_VULNERABILITE] s
WHERE NOT EXISTS (
    SELECT 1 FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = 255
      AND ISNULL(d.CODE_TYPE_VULNERABILITE,255) = ISNULL(s.CODE_TYPE_VULNERABILITE,255)
);
-- Insertion (pas d'ESTIMATION en source)
INSERT INTO EFFECTIFS_APPRENANTS (CODE_DIMENSION_APPRENANT, CODE_TYPE_EFFECTIFS_APPRENANTS, NB_APPR_G, NB_APPR_F, NB_APPR_T, ESTIMATION)
SELECT 
    d.CODE_DIMENSION_APPRENANT,
    11 AS CODE_TYPE_EFFECTIFS_APPRENANTS,
    COALESCE(s.NB_APPR_VULNERABLE_G,0),
    COALESCE(s.NB_APPR_VULNERABLE_F,0),
    COALESCE(s.NB_APPR_VULNERABLE_T, COALESCE(s.NB_APPR_VULNERABLE_G,0)+COALESCE(s.NB_APPR_VULNERABLE_F,0)),
    CAST(0 AS TINYINT)
FROM [BASE_SIGE_MINJEC].[dbo].[EFFECTIF_APPR_TYPE_VULNERABILITE] s
CROSS APPLY (
    SELECT CODE_DIMENSION_APPRENANT FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = 255
      AND ISNULL(d.CODE_TYPE_VULNERABILITE,255) = ISNULL(s.CODE_TYPE_VULNERABILITE,255)
) d;

-- =============================================
-- 14. MIGRATION EFFECTIF_APPR_TYPE_FORMATION
-- =============================================
-- Pré-population (Parcours fourni)
INSERT INTO DIMENSION_APPRENANT (
    CODE_CENTRE_DELEGATION, CODE_TYPE_ANNEE, CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,
    CODE_TYPE_SPECIALITE, CODE_TYPE_DUREE_FORMATION, CODE_TYPE_MODALITE_ACCOMP,
    CODE_TYPE_FORMATION, CODE_TYPE_NIVEAU_INSTRUCTION, CODE_TYPE_AGE,
    CODE_TYPE_ACCOMPAGNEMENT, CODE_TYPE_KITS_INSTALLATION, CODE_TYPE_HANDICAP,
    CODE_TYPE_MODE_FORMATION, CODE_TYPE_VULNERABILITE, CODE_TYPE_VIOLENCES
)
SELECT DISTINCT
    s.CODE_CENTRE_DELEGATION,
    s.CODE_TYPE_ANNEE,
    s.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,
    255, 255, 255,
    s.CODE_TYPE_FORMATION,
    255, 255,
    255, 255, 255,
    255, 255, 255
FROM [BASE_SIGE_MINJEC].[dbo].[EFFECTIF_APPR_TYPE_FORMATION] s
WHERE NOT EXISTS (
    SELECT 1 FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = ISNULL(s.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255)
      AND ISNULL(d.CODE_TYPE_FORMATION,255) = ISNULL(s.CODE_TYPE_FORMATION,255)
);
-- Insertion
INSERT INTO EFFECTIFS_APPRENANTS (CODE_DIMENSION_APPRENANT, CODE_TYPE_EFFECTIFS_APPRENANTS, NB_APPR_G, NB_APPR_F, NB_APPR_T, ESTIMATION)
SELECT 
    d.CODE_DIMENSION_APPRENANT,
    2 AS CODE_TYPE_EFFECTIFS_APPRENANTS,
    COALESCE(s.NB_APPR_FORM_G,0),
    COALESCE(s.NB_APPR_FORM_F,0),
    COALESCE(s.NB_APPR_FORM_T, COALESCE(s.NB_APPR_FORM_G,0)+COALESCE(s.NB_APPR_FORM_F,0)),
    CAST(ISNULL(s.ESTIMATION,0) AS TINYINT)
FROM [BASE_SIGE_MINJEC].[dbo].[EFFECTIF_APPR_TYPE_FORMATION] s
CROSS APPLY (
    SELECT CODE_DIMENSION_APPRENANT FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = ISNULL(s.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255)
      AND ISNULL(d.CODE_TYPE_FORMATION,255) = ISNULL(s.CODE_TYPE_FORMATION,255)
) d;

-- =============================================
-- 15. MIGRATION EFFECTIF_APPR_VICT_VIOLENCES
-- =============================================
-- Pré-population (Parcours = 255)
INSERT INTO DIMENSION_APPRENANT (
    CODE_CENTRE_DELEGATION, CODE_TYPE_ANNEE, CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,
    CODE_TYPE_SPECIALITE, CODE_TYPE_DUREE_FORMATION, CODE_TYPE_MODALITE_ACCOMP,
    CODE_TYPE_FORMATION, CODE_TYPE_NIVEAU_INSTRUCTION, CODE_TYPE_AGE,
    CODE_TYPE_ACCOMPAGNEMENT, CODE_TYPE_KITS_INSTALLATION, CODE_TYPE_HANDICAP,
    CODE_TYPE_MODE_FORMATION, CODE_TYPE_VULNERABILITE, CODE_TYPE_VIOLENCES
)
SELECT DISTINCT
    s.CODE_CENTRE_DELEGATION,
    s.CODE_TYPE_ANNEE,
    255,
    255, 255, 255,
    255, 255, 255,
    255, 255, 255,
    255, 255, s.CODE_TYPE_VIOLENCES
FROM [BASE_SIGE_MINJEC].[dbo].[EFFECTIF_APPR_VICT_VIOLENCES] s
WHERE NOT EXISTS (
    SELECT 1 FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = 255
      AND ISNULL(d.CODE_TYPE_VIOLENCES,255) = ISNULL(s.CODE_TYPE_VIOLENCES,255)
);
-- Insertion
INSERT INTO EFFECTIFS_APPRENANTS (CODE_DIMENSION_APPRENANT, CODE_TYPE_EFFECTIFS_APPRENANTS, NB_APPR_G, NB_APPR_F, NB_APPR_T, ESTIMATION)
SELECT 
    d.CODE_DIMENSION_APPRENANT,
    12 AS CODE_TYPE_EFFECTIFS_APPRENANTS,
    COALESCE(s.NB_APPR_VICT_VIOLENC_G,0),
    COALESCE(s.NB_APPR_VICT_VIOLENC_F,0),
    COALESCE(s.NB_APPR_VICT_VIOLENC_T, COALESCE(s.NB_APPR_VICT_VIOLENC_G,0)+COALESCE(s.NB_APPR_VICT_VIOLENC_F,0)),
    CAST(ISNULL(s.ESTIMATION,0) AS TINYINT)
FROM [BASE_SIGE_MINJEC].[dbo].[EFFECTIF_APPR_VICT_VIOLENCES] s
CROSS APPLY (
    SELECT CODE_DIMENSION_APPRENANT FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = 255
      AND ISNULL(d.CODE_TYPE_VIOLENCES,255) = ISNULL(s.CODE_TYPE_VIOLENCES,255)
) d;


-- =============================================
-- 16. MIGRATION EFFECTIF_APPR_NIVEAU_INSTRUCT
-- =============================================
-- Pré-population (Parcours fourni par la source)
INSERT INTO DIMENSION_APPRENANT (
    CODE_CENTRE_DELEGATION, CODE_TYPE_ANNEE, CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,
    CODE_TYPE_SPECIALITE, CODE_TYPE_DUREE_FORMATION, CODE_TYPE_MODALITE_ACCOMP,
    CODE_TYPE_FORMATION, CODE_TYPE_NIVEAU_INSTRUCTION, CODE_TYPE_AGE,
    CODE_TYPE_ACCOMPAGNEMENT, CODE_TYPE_KITS_INSTALLATION, CODE_TYPE_HANDICAP,
    CODE_TYPE_MODE_FORMATION, CODE_TYPE_VULNERABILITE, CODE_TYPE_VIOLENCES
)
SELECT DISTINCT
    s.CODE_CENTRE_DELEGATION,
    s.CODE_TYPE_ANNEE,
    s.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,
    255, 255, 255,
    255, s.CODE_TYPE_NIVEAU_INSTRUCTION, 255,
    255, 255, 255,
    255, 255, 255
FROM [BASE_SIGE_MINJEC].[dbo].[EFFECTIF_APPR_NIVEAU_INSTRUCT] s
WHERE NOT EXISTS (
    SELECT 1 FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = ISNULL(s.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255)
      AND ISNULL(d.CODE_TYPE_NIVEAU_INSTRUCTION,255) = ISNULL(s.CODE_TYPE_NIVEAU_INSTRUCTION,255)
);
-- Insertion des effectifs
INSERT INTO EFFECTIFS_APPRENANTS (CODE_DIMENSION_APPRENANT, CODE_TYPE_EFFECTIFS_APPRENANTS, NB_APPR_G, NB_APPR_F, NB_APPR_T, ESTIMATION)
SELECT 
    d.CODE_DIMENSION_APPRENANT,
    9 AS CODE_TYPE_EFFECTIFS_APPRENANTS,
    COALESCE(s.NB_APPR_ENT_G,0),
    COALESCE(s.NB_APPR_ENT_F,0),
    COALESCE(s.NB_APPR_ENT_T, COALESCE(s.NB_APPR_ENT_G,0)+COALESCE(s.NB_APPR_ENT_F,0)),
    CAST(ISNULL(s.ESTIMATION,0) AS TINYINT)
FROM [BASE_SIGE_MINJEC].[dbo].[EFFECTIF_APPR_NIVEAU_INSTRUCT] s
CROSS APPLY (
    SELECT CODE_DIMENSION_APPRENANT FROM DIMENSION_APPRENANT d
    WHERE d.CODE_CENTRE_DELEGATION = s.CODE_CENTRE_DELEGATION
      AND d.CODE_TYPE_ANNEE = s.CODE_TYPE_ANNEE
      AND ISNULL(d.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255) = ISNULL(s.CODE_TYPE_EFFECTIF_PARCOURS_APPRENANT,255)
      AND ISNULL(d.CODE_TYPE_NIVEAU_INSTRUCTION,255) = ISNULL(s.CODE_TYPE_NIVEAU_INSTRUCTION,255)
) d;

